name: Gather Eligible Repos

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * *" # Run daily at midnight UTC
env:
    IS_ORG: true

jobs:
    gather-repos:
        runs-on: ubuntu-latest
        steps:
            - name: Install sha256sum
              run: |
                    sudo apt-get update
                    sudo apt-get install -y coreutils
            

            - uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install PyGithub
                  pip install requests

            - name: Run repo gathering script
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  if [ -f "REPOS.json" ]; then
                    CHECKSUM=$(sha256sum REPOS.json)
                    echo "REPOS.json checksum: $CHECKSUM"                  
                  else:
                    CHECKSUM=""
                  fi

                  if [ "$IS_ORG" = true ] ; then
                      REPO_URL="https://api.github.com/orgs/${{ github.repository_owner }}/repos"
                  else
                      REPO_URL="https://api.github.com/users/${{ github.repository_owner }}/repos"
                  fi
                  python .github/scripts/gatherRepos.py "$REPO_URL"

                  if [ -f "REPOS.json" ]; then
                    CHECKSUM2=$(sha256sum REPOS.json)
                    echo "REPOS.json checksum: $CHECKSUM"                  
                  else:
                    CHECKSUM2=""
                  fi

                  if [ "$CHECKSUM" = "$CHECKSUM2" ]; then
                    echo "No changes detected. Exiting..."
                    exit 0                
                  fi
                
            - name: Commit and push changes
              run: |
                git config --global user.name "GitHub Actions"
                git config --global user.email "actions@github.com"
                git add REPOS.json
                git commit -m "Update REPOS.json"
                git push
                
            